### ISSUE TITLE
Is there a way that I can downgrade. I want to mess around with 1.21.1's code. 

### ISSUE THREAD

**Issue by awesomeshot5051** [dubfib/mcp-reimagined#1]
How can I downgrade it to 1.21.1? Do I just switch the version in the build.gradle? Or is it more complicated than that?

**Comment by dubfib** [comment]
> How can I downgrade it to 1.21.1? Do I just switch the version in the build.gradle? Or is it more complicated than that?

hey, so for the short version: its a bit more complicated than that (depending on mc version it can vary). i've already set the values for you in the zip i attached if you would like to use `1.21.1` (also cleaned up some unnecessary stuff). i've already tested it on intellij and works fine on my end. if you have anymore issues / questions, feel free to let me know.
[mcp-reimagined-1.21.1.zip](https://github.com/user-attachments/files/18055433/mcp-reimagined-1.21.1.zip)

**Comment by awesomeshot5051** [comment]
Thanks man. I'm sorry I didn't see this until today. I'll try it later today, but I appreciate it.

**Comment by dubfib** [comment]
yeah of course. if you have anymore issues / questions, let me know. going to close this issue for now because it seems resolved to me.
